[package]
name = "s6-manager"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dbus = "0.9.7"
nix = { version = "0.27.1", features = ["signal"] }
polling = "3.3.1"
