[package]
name = "color"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cssparser = "0.33.0"
palette = { version = "0.7.3", default-features = false, features = ["std"] }
