[language-server]
ccls = { command = "ccls" }

[language-server.grezi]
command = "grezi"
args = ["--lsp"]

[[language]]
name = "c"
auto-format = true
roots = ["compile_commands.json"]
language-servers = ["ccls"]

[[language]]
name = "cpp"
auto-format = true
language-servers = ["ccls"]

[[language]]
name = "grz"
scope = "scope.grz"
injection-regex = "grz"
file-types = ["grz"]
roots = []
auto-format = true
comment-token = "//"
indent = { tab-width = 4, unit = "    " }
language-servers = ["grezi"]

[[grammer]]
name = "grz"

[[language]]
name = "groff"
scope = "scope.groff"
injection-regex = "ms|groff|roff"
file-types = ["ms", "mom", "groff"]
roots = []
comment-token = ".\\\""
indent = { tab-width = 2, unit = "  " }

[[grammer]]
name = "groff"

[[language]]
name = "djot"
scope = "scope.djot"
injection-regex = "dj|djot"
file-types = ["dj"]
roots = []
comment-token = "{%"
indent = { tab-width = 4, unit = "    " }

[[grammar]]
name = "djot"
