[workspace]
members = [
  "listenbrainz-mpv",
  "rustbar",
  "tuigreet",
  "dconf-sys",
  "calloop-dbus",
  "dbus-dwl",
  "cosmic-osd",
]

[profile.release]
lto = true
strip = true
codegen-units = 1
panic = "abort"

[profile.dev]
incremental = false
