module.exports = grammar({
  name: 'dconfdwl',

  extras: _ => [],

  rules: {
    // TODO: add the actual grammar rules
    source_file: $ => choice(
      $.accel_profile,
      $.accel_speed,
      $.border_color,
      $.border_px,
      $.button_map,
      $.bypass_surface_visibility,
      $.click_method,
      $.disable_trackpad_while_typing,
      $.drag_lock,
      $.focus_color,
      $.fullscreen_bg,
      $.left_handed,
      $.log_level,
      $.middle_button_emulation,
      $.modkey,
      $.mouse_follows_focus,
      $.natural_scrolling,
      $.repeat_delay,
      $.repeat_rate,
      $.scroll_method,
      $.send_events_mode,
      $.sloppy_focus,
      $.tag_count,
      $.tap_to_click,
      $.tap_to_drag,
      $.xkb_options,
    ),
    accel_profile: _ =>    "/dotfiles/dwl/accel-profile",
    accel_speed: _ =>    "/dotfiles/dwl/accel-speed",
    border_color: _ =>    "/dotfiles/dwl/border-color",
    border_px: _ =>    "/dotfiles/dwl/border-px",
    button_map: _ =>    "/dotfiles/dwl/button-map",
    bypass_surface_visibility: _ =>    "/dotfiles/dwl/bypass-surface-visibility",
    click_method: _ =>    "/dotfiles/dwl/click-method",
    disable_trackpad_while_typing: _ =>    "/dotfiles/dwl/disable-trackpad-while-typing",
    drag_lock: _ =>    "/dotfiles/dwl/drag-lock",
    focus_color: _ =>    "/dotfiles/dwl/focus-color",
    fullscreen_bg: _ =>    "/dotfiles/dwl/fullscreen-bg",
    left_handed: _ =>    "/dotfiles/dwl/left-handed",
    log_level: _ =>    "/dotfiles/dwl/log-level",
    middle_button_emulation: _ =>    "/dotfiles/dwl/middle-button-emulation",
    modkey:    _ => "/dotfiles/dwl/modkey",
    mouse_follows_focus: _ =>    "/dotfiles/dwl/mouse-follows-focus",
    natural_scrolling: _ =>    "/dotfiles/dwl/natural-scrolling",
    repeat_delay: _ =>    "/dotfiles/dwl/repeat-delay",
    repeat_rate: _ =>    "/dotfiles/dwl/repeat-rate",
    scroll_method: _ =>    "/dotfiles/dwl/scroll-method",
    send_events_mode: _ =>    "/dotfiles/dwl/send-events-mode",
    sloppy_focus: _ =>    "/dotfiles/dwl/sloppy-focus",
    tag_count: _ =>    "/dotfiles/dwl/tag-count",
    tap_to_click: _ =>    "/dotfiles/dwl/tap-to-click",
    tap_to_drag: _ =>    "/dotfiles/dwl/tap-to-drag",
    xkb_options: _ =>    "/dotfiles/dwl/xkb-options",
  }
});

