[package]
name = "rustbar"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "rustbar"
crate-type = ["staticlib", "rlib"]

# [[bin]]
# name = "rustbar"
# path = "src/i3-main.rs"

[dependencies]
calloop = "0.10.5"
calloop-dbus = { path = "../calloop-dbus" }
dbus = "0.9.7"
dirs = "4.0.0"
gsettings-macro = "0.1.18"
nix = { version = "0.26.2", default-features = false, features = ["inotify"] }
num_enum = "0.5.11"
rand = { version = "0.8.5", default-features = false, features = ["std"] }
time = { version = "0.3.20", features = ["local-offset", "formatting"] }
tz-rs = "0.6.14"
dconf-sys = { path = "../dconf-sys" }
glib = "0.17.9"

[features]
i3bar = []
